FROM python:3.7-buster
ENV PYTHONUNBUFFERED 1
WORKDIR /code

COPY requirements.txt .
RUN apt-get update \
	&& pip install --upgrade pip \
	&& pip install -r requirements.txt
COPY . .

CMD ["python", "client.py"]