FROM balenalib/raspberry-pi2-debian-python:3.7

RUN [ "cross-build-start" ]
WORKDIR /code

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN [ "cross-build-end" ]
CMD [ "python", "client.py" ]